In [1]:
import numpy as np

In [2]:
vector = np.arange(5)

In [3]:
vector * 10

array([ 0, 10, 20, 30, 40])

In [4]:
np.arange(24).reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
import pandas as pd

In [6]:
cars = pd.read_csv('cars (1).csv')

In [7]:
cars.head()

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
0,14.0,8,350,165,4209,12,1972,US.
1,31.9,4,89,71,1925,14,1980,Europe.
2,17.0,8,302,140,3449,11,1971,US.
3,15.0,8,400,150,3761,10,1971,US.
4,30.5,4,98,63,2051,17,1978,US.


In [8]:
cars.values # .values will convert a dataframe into a numpy array

array([[14.0, 8, '350', ..., 12, 1972, ' US.'],
       [31.9, 4, '89', ..., 14, 1980, ' Europe.'],
       [17.0, 8, '302', ..., 11, 1971, ' US.'],
       ...,
       [22.0, 6, '232', ..., 15, 1983, ' US.'],
       [18.0, 6, '232', ..., 16, 1972, ' US.'],
       [22.0, 6, '250', ..., 15, 1977, ' US.']],
      shape=(261, 8), dtype=object)

In [9]:
mat1 = np.random.randint(10, 51, size = (3,3))
mat2 = np.random.randint(50, 100, size = (3,3))

In [10]:
mat1

array([[14, 28, 20],
       [34, 27, 12],
       [35, 21, 25]], dtype=int32)

In [11]:
mat2

array([[68, 55, 61],
       [74, 73, 92],
       [59, 88, 74]], dtype=int32)

In [12]:
#addition of matrices
mat1 + mat2 #np.add(mat1, mat2)

array([[ 82,  83,  81],
       [108, 100, 104],
       [ 94, 109,  99]], dtype=int32)

In [13]:
mat1 + 10

array([[24, 38, 30],
       [44, 37, 22],
       [45, 31, 35]], dtype=int32)

In [14]:
#subtraction of matrices
mat1 - mat2   #np.subtract(mat1, mat2)

array([[-54, -27, -41],
       [-40, -46, -80],
       [-24, -67, -49]], dtype=int32)

In [15]:
mat2 - mat1

array([[54, 27, 41],
       [40, 46, 80],
       [24, 67, 49]], dtype=int32)

In [16]:
#division of matrices
mat1 / 10

array([[1.4, 2.8, 2. ],
       [3.4, 2.7, 1.2],
       [3.5, 2.1, 2.5]])

In [17]:
mat1 / mat2  #np.divide(mat1, mat2)

array([[0.20588235, 0.50909091, 0.32786885],
       [0.45945946, 0.36986301, 0.13043478],
       [0.59322034, 0.23863636, 0.33783784]])

In [18]:
#element-wise multiplication or Hadamard product
mat1 * mat2   #np.multiply(mat1, mat2)

array([[ 952, 1540, 1220],
       [2516, 1971, 1104],
       [2065, 1848, 1850]], dtype=int32)

In [19]:
#actual matrix multiplication : Dot product
mat1 @ mat2 #np.dot(mat1, mat2)

array([[4204, 4574, 4910],
       [5018, 4897, 5446],
       [5409, 5658, 5917]], dtype=int32)

In [20]:
mat1

array([[14, 28, 20],
       [34, 27, 12],
       [35, 21, 25]], dtype=int32)

In [21]:
#Transpose of a matrix
mat1.T

array([[14, 34, 35],
       [28, 27, 21],
       [20, 12, 25]], dtype=int32)

In [22]:
#matrix rank : helps us to identify duplicate or redundant data
np.linalg.matrix_rank(mat1)

np.int64(3)

In [23]:
#determinant of a matrix : whether a matrix is singular or not
np.linalg.det(mat1)

np.float64(-10738.000000000011)

In [24]:
mat3 = np.arange(9).reshape(3,3)

In [25]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.linalg.det(mat3)

np.float64(0.0)

In [27]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
#inverse of a matrix
mat1_inv = np.linalg.inv(mat1)

In [ ]:
mat1_inv

In [ ]:
np.round((mat1_inv @ mat1), 2)

In [ ]:
np.linalg.inv(mat3)

In [ ]:
matrix = np.array([[3, -2],
                   [1, 0]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Original Matrix: ")
print(matrix)
print('\nEigenvalues: ')
print(eigenvalues)
print('\nEigenvectors: ')
print(eigenvectors)

In [ ]:
np.dot(matrix, [0.89442719, 0.4472136])

In [ ]:
np.array([0.89442719, 0.4472136]) * 2

In [ ]:


                                   # HANDSON



In [ ]:
#1) to create 3X3 matrix using numpy with random numbers in the range of 1-100

# Matrix Operation Scaler operation

# add 2
# substract 3
# divide 4
# multiply 2

In [ ]:
import numpy as np
import pandas as pd

arr=np.random.randint(1,100,9).reshape(3,3)
print(arr)

In [ ]:
arr+2

In [ ]:
arr - 3

In [ ]:
arr/4

In [ ]:
arr//4

In [ ]:
arr*2

In [ ]:
#2 to create 4X4 matrix using numpy with random numbers in the range of 1-100 and 
#print all the odd numbers using looping
#print all the even numbers

In [ ]:
a=np.random.randint(1,100,(4,4))
a

In [ ]:
print("\nOdd Numbers:")
for row in a:
    for num in row:
        if num % 2 !=0:
            print(num, end=" ")

In [ ]:
print("\nEven Numbers:")
for row in a:
    for num in row:
        if num % 2 ==0:
            print(num, end=" ")

In [ ]:
#3 to create 4X4 matrix using numpy with random numbers in the range of 1-100 
#and print mean for each row
a=np.random.randint(1,100,(4,4))
a

In [ ]:
mean_list=[]
for i in a:
    matrix_mean=i.mean()
    mean_list.append(matrix_mean)
mean_list

In [ ]:
# create two 2X2 matrix

# add the matrix
# multiply matrix
# divide matrix
# substract matrix
matrix_a=np.random.randint(1,10,(2,2))
matrix_b=np.random.randint(1,10,(2,2))
print(matrix_a)
print(matrix_b)
matrix_division = matrix_a / matrix_b


print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nMatrix A / Matrix B (element-wise):")
print(matrix_division)

matrix_subtraction = matrix_a - matrix_b


print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nMatrix A - Matrix B (element-wise):")
print(matrix_subtraction)

In [ ]:
# prove for transpose of a matrix, if below statments are true or False

#   (A’)’ = A
#   K x A’ = (KA)’ # k is any constant value
#   (A+B)’ = A’ + B’
#   (AB)’ = B’A’

a=np.random.randint(1,10,(2,2))
b=np.random.randint(1,10,(2,2))

#   (A’)’ = A
a.T.T==a

In [ ]:
a

In [ ]:
a.T.T

In [ ]:
#   K x A’ = (KA)’ # k is any constant value

(a.T)*3==(3*a).T

In [ ]:
#   (A+B)’ = A’ + B’
(a+b).T==a.T+b.T

In [ ]:
#   (AB)’ = B’A’
(a*b).T==b.T*a.T

In [ ]:
(a*b).T

In [ ]:
b.T*a.T

In [ ]:
#to create 4X4 matrix using numpy with random numbers in the range of 1-100 and
#print all the even numers which are less than 50

In [ ]:
m = np.random.randint(1, 101, size=(4, 4))
m

In [ ]:
for i in m:
  for j in i:
    if j%2==0 and j<50:
      print(j)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Create a 1D NumPy array with 10 random integers between 1 and 50.
#Using a for loop, print all numbers greater than the mean of the array.


In [ ]:
arr = np.random.randint(1, 51, 10)
arr

In [ ]:
mean_value = arr.mean()
mean_value

In [ ]:
for num in arr:
    if num > mean_value:
        print(num)

In [ ]:
#Create a NumPy array of 15 random integers between 1 and 100.
#Using a while loop, find and print the maximum value in the array.without using any inbuilt function

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, 15)
print("Array:", arr)

In [ ]:
max_val = arr[0] #90
i = 1 

while i < len(arr):
    if arr[i] > max_val: #80>90  
        max_val = arr[i]   
    i += 1 #i=i+1

print("Maximum value:", max_val)

In [ ]:
# Print
# *****
# ***
# *

In [ ]:
i=5

while i>0:
  print(i)
  i-= 2

In [ ]:
i=5

while i>0:
  print(i*"*")
  i-= 2

In [ ]:
# a= "RCRCAAIRA" , create a dictionary where key is every unique character 
# and value is the number of times each unique character is repeating

In [32]:
a = "RCRCAAIRA"
d1 = {}
for i in a:
    if i not in d1:
        d1[i] = 1
    else :
        d1[i] += 1
    print(d1)

{'R': 1}
{'R': 1, 'C': 1}
{'R': 2, 'C': 1}
{'R': 2, 'C': 2}
{'R': 2, 'C': 2, 'A': 1}
{'R': 2, 'C': 2, 'A': 2}
{'R': 2, 'C': 2, 'A': 2, 'I': 1}
{'R': 3, 'C': 2, 'A': 2, 'I': 1}
{'R': 3, 'C': 2, 'A': 3, 'I': 1}


In [34]:
# Create a string and store your name in it using userinput
# print the length of the string without using any inbuilt function

In [37]:
a = input("Enter Your Name:")
count=0
for i in a:
  count+=1
count

Enter Your Name: Yashmeen


8