In [1]:
#Numpy -> 
#numerical computation 
#we work on arrays through numpy  
#c and c++ libraries
#in python there is no array but we import arrays through numpy 

In [2]:
#Why arrays? why not lists?
# for calculations
# lists acquire more space because of different datatypes
# arrays are much faster comparing to lists
#syntax_>
import numpy as np
variable = np.array([1,2,3,4,5])

In [3]:
variable

array([1, 2, 3, 4, 5])

In [4]:
variable.dtype

dtype('int64')

In [5]:
arr = np.array([1,2,3,"Yashmeen"])
arr

array(['1', '2', '3', 'Yashmeen'], dtype='<U21')

In [6]:
list1 = [1,2,3,4]

In [7]:
list2 = [5,6,7,8]

In [8]:
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [9]:
arr1 = np.array([1,2,3,4])

In [10]:
arr2 = np.array([5,6,7,8])

In [11]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1/arr2)
print(arr1*arr2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[0.2        0.33333333 0.42857143 0.5       ]
[ 5 12 21 32]


In [12]:
#Total
arr22= np.array([1,2,55,89])
total = arr22.sum()
total

np.int64(147)

In [13]:
total13 = np.sum(arr22)
total13

np.int64(147)

In [14]:
#Mean
mean= arr22.mean()
mean

np.float64(36.75)

In [15]:
#Sort
sort = np.sort(arr22)
print(sort)

[ 1  2 55 89]


In [16]:
decending = np.sort(arr22) [::-2]
decending

array([89,  2])

In [17]:
#Median
median= np.median(arr22)
median

np.float64(28.5)

In [18]:
#flatten = it'll flat any array like a 3d array to '1D' array immidiately

In [19]:
arr5 = np.array([
    [[1,2,3],[4,5,6]],
    [[9,8,7],[7,6,1]]
])


In [20]:
flat = arr5.flatten()
flat

array([1, 2, 3, 4, 5, 6, 9, 8, 7, 7, 6, 1])

In [21]:
#Types of arrays -> 
#0D array -> only one point exists (dot)
arr0d = np.array(2)
arr0d.ndim #n dimension

0

In [22]:
#1D -> list
arr1d = np.array([1,2,3])
arr1d.ndim

1

In [23]:
arr1d

array([1, 2, 3])

In [24]:
#2d -> rows and columns
arr2d = np.array([[1,2],[3,4]])

In [25]:
arr2d

array([[1, 2],
       [3, 4]])

In [27]:
arr2d.ndim

2

In [28]:
arr3d = np.array([
    [[1,2],[3,4]],
    [[6,7],[8,9]]
])

In [29]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [30]:
arr3d.ndim

3

In [31]:
arr3 = np.array([
    [[2,4],[4,5]],
    [[3,7],[8,9]],
    [[9,6],[7,8]]
])

In [32]:
arr3

array([[[2, 4],
        [4, 5]],

       [[3, 7],
        [8, 9]],

       [[9, 6],
        [7, 8]]])

In [33]:
#shape 
arr0d.shape

()

In [34]:
arr1d.shape


(3,)

In [35]:
arr2d


array([[1, 2],
       [3, 4]])

In [36]:
arr2d.shape

(2, 2)

In [37]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [38]:
arr3d.shape

(2, 2, 2)

In [39]:
arr3.shape

(3, 2, 2)

In [40]:
#Accessing values with index                                                                           
arr1d

array([1, 2, 3])

In [41]:
arr1d[1]

np.int64(2)

In [42]:
arr2d

array([[1, 2],
       [3, 4]])

In [43]:
arr2d[(1,0)]

np.int64(3)

In [44]:
arr3

array([[[2, 4],
        [4, 5]],

       [[3, 7],
        [8, 9]],

       [[9, 6],
        [7, 8]]])

In [45]:
arr3[(2,0,1)]

np.int64(6)

In [46]:
#Slicing
arr1d

array([1, 2, 3])

In [47]:
arr1d[0:2]

array([1, 2])

In [48]:
arr2d

array([[1, 2],
       [3, 4]])

In [49]:
arr2d[0,0:2]

array([1, 2])

In [50]:
arr2d[0:2,0:1]

array([[1],
       [3]])

In [51]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [52]:
arr3d[1,0:1]

array([[6, 7]])

In [53]:
arr3d[0:2,0:2,1]

array([[2, 4],
       [7, 9]])

In [54]:
arr3

array([[[2, 4],
        [4, 5]],

       [[3, 7],
        [8, 9]],

       [[9, 6],
        [7, 8]]])

In [55]:
arr3[0:3,0:2,0]

array([[2, 4],
       [3, 8],
       [9, 7]])

In [66]:
arr3[0:3,0]

array([[2, 4],
       [3, 7],
       [9, 6]])

In [72]:
arr3[0:3,0:2,1]

array([[4, 5],
       [7, 9],
       [6, 8]])

In [73]:
list3 = [1,2,3,4,5,6,7,8,9,10]

In [179]:
list3[::2]

[1, 3, 5, 7, 9]

In [78]:
#Reshape ->
#to change the shape of matrix


In [79]:
arr2 = np.array([[3,4],[5,6]])
arr2

array([[3, 4],
       [5, 6]])

In [80]:
arr2.reshape(4)

array([3, 4, 5, 6])

In [81]:
arr69 = np.array([1,2,3,4,5,6, 7,8,9,0,1,2])

In [82]:
arr69

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [83]:
arr69.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [84]:
arr69.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [86]:
#lcm is used for reshaping generally for example there were 12 elements above and lcm of 12 is 2,2,3
#-------

In [95]:
#np.zeros() it creates a numpy array where all elements are zeroes
#1d ->
arr1D = np.zeros(5,dtype='int')

In [96]:
arr1D

array([0, 0, 0, 0, 0])

In [104]:
arr2 = np.zeros((8,69),dtype='object')

In [106]:
arr2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [109]:
arr30 = np.zeros([4,5,4],dtype='int')

In [110]:
arr30

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [113]:
#np.ones() -  it creates a numpy array where all elements are ones
arr1D = np.ones(6,dtype='int')

In [114]:
arr1D

array([1, 1, 1, 1, 1, 1])

In [117]:
arr2 = np.ones((2,3
               ),dtype='float')

In [56]:
arr2

array([5, 6, 7, 8])

In [119]:
arr30 = np.ones([4,6,4],dtype='object')

In [120]:
arr30

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=object)

In [121]:
# np.full

In [124]:
a = np.full(100,3)

In [125]:
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [130]:
#np.identity(size) - where diagonals are 1 and else are 0
#it is always a SQUARE matrix

In [131]:
b = np.identity(100,dtype='int')
b

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(100, 100))

In [133]:
#np.eye()  -> it is like identity matrix but can be used for rectangular matrix 

In [141]:
aankh = np.eye(2,4,dtype = 'int')      
aankh            

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

In [142]:
aank = np.eye(5,dtype = 'int')      
aank            

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [143]:
#random is a module in numpy
#np.random.randint()
#rand and int means random integer
x= np.random.randint(1,100)   #it will give integers from 1 to 99 any!
x 

9

In [144]:
#it will always give a new random number if you rerun it

In [148]:
#if we need more than 1 values then ->
y = np.random.randint(1, 100, size = 30) #30 random no.s

In [146]:
y

array([51, 47, 46, 79, 49, 39,  4, 95, 11, 56, 14, 67, 28, 41, 28, 59, 48,
       71, 62,  4, 56, 73, 37, 48, 61, 70, 36,  6,  4, 70], dtype=int32)

In [149]:
#working of choice 
dice = [1,2,3,4,5,6]
ludo = np.random.choice(dice)

In [150]:
ludo

np.int64(2)

In [157]:
num = [3,4,7,9]
num1 = np.random.choice(num)

In [158]:
num1

np.int64(7)

In [57]:


                                     #HANDSON



In [58]:
# Ques1 : Create a Numpy Array with numpy.array module and 
# with a datatype integer and float

In [59]:
import numpy as np

In [63]:
arr1 = np.array([10,20,30,40,50,60],dtype=int)

In [66]:
print("integer array-",arr1)

integer array- [10 20 30 40 50 60]


In [67]:
arr2 = np.array([10,20,30,40,50,60],dtype=float)
print("float array-",arr2)

float array- [10. 20. 30. 40. 50. 60.]


In [68]:
# Ques2 : Create numpy arrays that have zero,one,two,three dimensions respectively 
# also print the shape and dimensions of the numpy array's created above

In [70]:
zero_dim = np.array(33)
print(zero_dim)

33


In [71]:
print(zero_dim.ndim)

0


In [72]:
print(zero_dim.shape)

()


In [73]:
one_dim = np.array([1,2,3,4,5])
print(one_dim)

[1 2 3 4 5]


In [74]:
print(one_dim.ndim)

1


In [75]:
print(one_dim.shape)

(5,)


In [77]:
two_dim= np.array([[1,2,3],[4,5,6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [78]:
print(two_dim.ndim)

2


In [79]:
print(two_dim.shape)

(2, 3)


In [83]:
three_dim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [84]:
print(three_dim.ndim)

3


In [85]:
print(three_dim.shape)

(2, 2, 3)


In [86]:
# Ques3 : Create a 2X2,3X3, 4X4 identity matrix

In [87]:
two = np.identity(2,dtype='int')

In [89]:
print(two)

[[1 0]
 [0 1]]


In [90]:
three = np.identity(3,dtype='int')
print(three)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [93]:
four = np.identity(4,dtype=int)
print(four)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [94]:
#Ques4: Create a numpy array of shape 2X5 that has all elements as zero

In [101]:
zero = np.zeros([2,5],dtype=int)
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [102]:
#Ques5: Create a numpy array of shape 3X5 that has all elements as 5

In [107]:
full = np.full((3,5),5,dtype=int)
print(full)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [108]:
# Ques 6 : Create a numpy array with random integers in the range
# 0-100 and sample size as 25

In [109]:
r = np.random.randint(1, 100, size = 25) 

In [110]:
print(r)

[71 17 67  7 30 29 41 15 74  9 74 41 23 90 18 20 11  7 51 96 89 47 22 60
 42]


In [111]:
# Ques 7 : Create a numpy array with random integers in the range
# 0-100 and in shape : 2x3 and reshape the array : 3x2 and 
# print the updated shape

In [116]:
r = np.random.randint(1,100,size=(2,3)) 

In [117]:
print(r)

[[92 93 57]
 [39 43 35]]


In [118]:
new_r = r.reshape(3,2)
print(new_r)

[[92 93]
 [57 39]
 [43 35]]


In [119]:
new_r.shape

(3, 2)

In [120]:
# Ques8 : Create a numpy array with shape 3x3 and all elements as 1

In [122]:
narr = np.ones((3,3),dtype=int)
print(narr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
